#!/usr/bin/env bash
echo "Building workspaces, please wait ..." | wofi --dmenu & wofi_pid=$!

swaymsg 'workspace 1'
sway-toolwait -v -n 'brave-browser'
sway-toolwait -v 'code'
sway-toolwait -v 'kitty'
swaymsg 'focus prev'
swaymsg 'resize set width 2500px'

swaymsg 'workspace 2'
sway-toolwait -v 'spotify'

swaymsg 'workspace 3'
sway-toolwait -v 'thunar'

swaymsg 'workspace 1'
kill $wofi_pid
